name: ashiq
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  percent_indicator : ^4.2.3
  flutter:
    sdk: flutter
  loading_animation_widget:
  flutter_spinkit: ^5.2.0


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
 
  assets:
    - assets/
    - assets/data/
    - assets/images/
